// frontend/src/components/layout/SettingsDialog.vue
<script setup lang="ts">
import { computed, reactive, shallowRef } from 'vue'
import { ElMessage } from 'element-plus'

import { useSettingsStore, type SettingsForm } from '../../stores/settings'

const settings = useSettingsStore()
const saving = shallowRef(false)

const form = reactive<SettingsForm>({
  provider: '',
  api_key: '',
  model: '',
  base_url: '',
})

function findCatalog(provider: string) {
  return settings.catalog.find((item) => item.id === provider)
}

function findConfig(provider: string) {
  return settings.configs.find((row) => row.provider === provider)
}

function applyProvider(provider: string) {
  const meta = findCatalog(provider)
  const existing = findConfig(provider)
  form.provider = provider
  form.api_key = ''
  form.model = existing?.model || meta?.default_model || ''
  form.base_url = existing?.base_url || meta?.default_base_url || ''
}

async function onOpen() {
  try {
    await settings.load()
  } catch (e) {
    ElMessage.error(e instanceof Error ? e.message : '加载设置失败')
    return
  }
  const firstId = settings.catalog[0]?.id ?? ''
  applyProvider(settings.activeProvider || firstId)
}

function onProviderChange(provider: string) {
  applyProvider(provider)
}

const keyPlaceholder = computed(() => {
  const row = findConfig(form.provider)
  if (row?.has_key && row.api_key_masked) return row.api_key_masked
  return '请输入 API Key'
})

const requiresBaseUrl = computed(() => Boolean(findCatalog(form.provider)?.requires_base_url))

const hasSavedKey = computed(() => Boolean(findConfig(form.provider)?.has_key))

const basePlaceholder = computed(() => {
  const meta = findCatalog(form.provider)
  if (meta?.requires_base_url) return '必填，例如 https://api.example.com/v1'
  return meta?.default_base_url || '可选'
})

const canSave = computed(() => {
  if (!form.provider || !form.model.trim()) return false
  if (requiresBaseUrl.value && !form.base_url.trim()) return false
  const row = findConfig(form.provider)
  if (!form.api_key.trim() && !row?.has_key) return false
  return true
})

const saveHint = computed(() => {
  if (requiresBaseUrl.value && !form.base_url.trim()) {
    return 'OpenAI Compatible 必须填写 Base URL'
  }
  const row = findConfig(form.provider)
  if (!form.api_key.trim() && !row?.has_key) return '请填写 API Key'
  if (!form.model.trim()) return '请填写模型名称'
  return ''
})

async function onSave() {
  if (!canSave.value) return
  saving.value = true
  try {
    await settings.save({
      provider: form.provider,
      api_key: form.api_key,
      model: form.model.trim(),
      base_url: form.base_url.trim(),
    })
    ElMessage.success('已保存并设为当前模型')
    settings.closeSettings()
  } catch (e) {
    ElMessage.error(e instanceof Error ? e.message : '保存失败')
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <el-dialog
    v-model="settings.settingsOpen"
    title="模型设置"
    width="520px"
    @open="onOpen"
  >
    <el-form label-position="top">
      <el-form-item label="供应商">
        <el-select
          v-model="form.provider"
          class="w-full"
          placeholder="选择供应商"
          :disabled="settings.loading"
          @change="onProviderChange"
        >
          <el-option
            v-for="item in settings.catalog"
            :key="item.id"
            :label="item.label"
            :value="item.id"
          />
        </el-select>
      </el-form-item>
      <el-form-item label="API Key">
        <el-input
          v-model="form.api_key"
          type="password"
          show-password
          autocomplete="off"
          :placeholder="keyPlaceholder"
          :disabled="settings.loading"
        />
        <p
          v-if="hasSavedKey"
          class="text-xs text-slate-500 mt-1"
        >
          留空则保留已保存的密钥
        </p>
      </el-form-item>
      <el-form-item label="模型">
        <el-input v-model="form.model" :disabled="settings.loading" />
      </el-form-item>
      <el-form-item label="Base URL">
        <el-input
          v-model="form.base_url"
          :placeholder="basePlaceholder"
          :disabled="settings.loading"
        />
        <p
          v-if="requiresBaseUrl && !form.base_url.trim()"
          class="text-xs text-amber-600 mt-1"
        >
          OpenAI Compatible 必须填写 Base URL
        </p>
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="settings.closeSettings()">取消</el-button>
      <el-button
        type="primary"
        :loading="saving"
        :disabled="!canSave || settings.loading"
        @click="onSave"
      >
        保存并使用
      </el-button>
      <p v-if="saveHint && !canSave" class="text-xs text-slate-500 mt-2 text-left">
        {{ saveHint }}
      </p>
    </template>
  </el-dialog>
</template>

// frontend-react/src/components/layout/SettingsDialog.tsx
import { useEffect, useState } from 'react'

import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useSettingsStore, type SettingsForm } from '@/stores/settings'

const emptyForm: SettingsForm = { provider: '', api_key: '', model: '', base_url: '' }

export default function SettingsDialog() {
  const settingsOpen = useSettingsStore((s) => s.settingsOpen)
  const closeSettings = useSettingsStore((s) => s.closeSettings)
  const load = useSettingsStore((s) => s.load)
  const save = useSettingsStore((s) => s.save)
  const catalog = useSettingsStore((s) => s.catalog)
  const configs = useSettingsStore((s) => s.configs)
  const loading = useSettingsStore((s) => s.loading)

  const [form, setForm] = useState<SettingsForm>(emptyForm)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)

  function findCatalog(provider: string) {
    return catalog.find((item) => item.id === provider)
  }

  function findConfig(provider: string) {
    return configs.find((row) => row.provider === provider)
  }

  function applyProvider(provider: string) {
    const meta = findCatalog(provider)
    const existing = findConfig(provider)
    setForm({
      provider,
      api_key: '',
      model: existing?.model || meta?.default_model || '',
      base_url: existing?.base_url || meta?.default_base_url || '',
    })
  }

  useEffect(() => {
    if (!settingsOpen) return
    setError(null)
    setNotice(null)
    let active = true
    load()
      .then(() => {
        if (!active) return
        const state = useSettingsStore.getState()
        const firstId = state.catalog[0]?.id ?? ''
        applyProvider(state.activeProvider || firstId)
      })
      .catch((e: unknown) => {
        if (active) setError(e instanceof Error ? e.message : '加载设置失败')
      })
    return () => {
      active = false
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [settingsOpen])

  const requiresBaseUrl = Boolean(findCatalog(form.provider)?.requires_base_url)
  const hasSavedKey = Boolean(findConfig(form.provider)?.has_key)

  const keyPlaceholder = (() => {
    const row = findConfig(form.provider)
    if (row?.has_key && row.api_key_masked) return row.api_key_masked
    return '请输入 API Key'
  })()

  const basePlaceholder = (() => {
    const meta = findCatalog(form.provider)
    if (meta?.requires_base_url) return '必填，例如 https://api.example.com/v1'
    return meta?.default_base_url || '可选'
  })()

  const canSave = (() => {
    if (!form.provider || !form.model.trim()) return false
    if (requiresBaseUrl && !form.base_url.trim()) return false
    const row = findConfig(form.provider)
    if (!form.api_key.trim() && !row?.has_key) return false
    return true
  })()

  const saveHint = (() => {
    if (requiresBaseUrl && !form.base_url.trim()) return 'OpenAI Compatible 必须填写 Base URL'
    const row = findConfig(form.provider)
    if (!form.api_key.trim() && !row?.has_key) return '请填写 API Key'
    if (!form.model.trim()) return '请填写模型名称'
    return ''
  })()

  async function onSave() {
    if (!canSave) return
    setSaving(true)
    setError(null)
    try {
      await save({
        provider: form.provider,
        api_key: form.api_key,
        model: form.model.trim(),
        base_url: form.base_url.trim(),
      })
      setNotice('已保存并设为当前模型')
      closeSettings()
    } catch (e) {
      setError(e instanceof Error ? e.message : '保存失败')
    } finally {
      setSaving(false)
    }
  }

  return (
    <Dialog
      open={settingsOpen}
      onOpenChange={(open) => {
        if (!open) closeSettings()
      }}
    >
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>模型设置</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label>供应商</Label>
            <Select value={form.provider} onValueChange={applyProvider} disabled={loading}>
              <SelectTrigger className="w-full">
                <SelectValue placeholder="选择供应商" />
              </SelectTrigger>
              <SelectContent>
                {catalog.map((item) => (
                  <SelectItem key={item.id} value={item.id}>
                    {item.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="settings-api-key">API Key</Label>
            <Input
              id="settings-api-key"
              type="password"
              autoComplete="off"
              placeholder={keyPlaceholder}
              disabled={loading}
              value={form.api_key}
              onChange={(e) => setForm((f) => ({ ...f, api_key: e.target.value }))}
            />
            {hasSavedKey && <p className="text-xs text-slate-500">留空则保留已保存的密钥</p>}
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="settings-model">模型</Label>
            <Input
              id="settings-model"
              disabled={loading}
              value={form.model}
              onChange={(e) => setForm((f) => ({ ...f, model: e.target.value }))}
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="settings-base-url">Base URL</Label>
            <Input
              id="settings-base-url"
              placeholder={basePlaceholder}
              disabled={loading}
              value={form.base_url}
              onChange={(e) => setForm((f) => ({ ...f, base_url: e.target.value }))}
            />
            {requiresBaseUrl && !form.base_url.trim() && (
              <p className="text-xs text-amber-600">OpenAI Compatible 必须填写 Base URL</p>
            )}
          </div>

          {error && <p className="text-sm text-[var(--color-destructive)]">{error}</p>}
          {notice && !error && <p className="text-sm text-[var(--color-primary)]">{notice}</p>}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={closeSettings}>
            取消
          </Button>
          <div className="flex flex-col items-end gap-1">
            <Button disabled={!canSave || loading || saving} onClick={onSave}>
              {saving ? '保存中…' : '保存并使用'}
            </Button>
            {saveHint && !canSave && <p className="text-xs text-slate-500">{saveHint}</p>}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
