// frontend/src/components/layout/SidebarFooter.vue
<script setup lang="ts">
import { Setting, UserFilled } from '@element-plus/icons-vue'
import { useRouter } from 'vue-router'

import { useAuthStore } from '../../stores/auth'
import { useSettingsStore } from '../../stores/settings'

const auth = useAuthStore()
const settings = useSettingsStore()
const router = useRouter()

async function onLogout() {
  await auth.logout()
  await router.replace({ name: 'login' })
}

function goAdminUsers() {
  void router.push({ name: 'admin-users' })
}

function goAdminDatabases() {
  void router.push({ name: 'admin-databases' })
}

function onMenuCommand(cmd: string) {
  if (cmd === 'logout') void onLogout()
  else if (cmd === 'admin') goAdminUsers()
  else if (cmd === 'admin-databases') goAdminDatabases()
}
</script>

<template>
  <div
    class="flex h-14 shrink-0 items-center justify-between gap-2 border-t border-[var(--color-border)] bg-[var(--color-card)] px-3"
  >
    <el-dropdown trigger="click" @command="onMenuCommand">
      <button
        type="button"
        class="flex min-w-0 cursor-pointer items-center gap-2 rounded-lg px-2 py-1.5 text-left transition-colors duration-200 hover:bg-slate-50"
      >
        <el-avatar :size="30" class="shrink-0 !bg-[var(--color-primary)]">
          <el-icon><UserFilled /></el-icon>
        </el-avatar>
        <span class="max-w-[7rem] truncate text-sm font-medium text-[var(--color-foreground)]">
          {{ auth.username || '用户' }}
        </span>
      </button>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item disabled>资料（占位）</el-dropdown-item>
          <el-dropdown-item v-if="auth.role === 'admin'" command="admin">用户管理</el-dropdown-item>
          <el-dropdown-item v-if="auth.role === 'admin'" command="admin-databases">数据库管理</el-dropdown-item>
          <el-dropdown-item divided command="logout">退出登录</el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>

    <el-button
      text
      circle
      class="!h-10 !w-10"
      aria-label="设置"
      @click="settings.openSettings()"
    >
      <el-icon :size="18"><Setting /></el-icon>
    </el-button>
  </div>
</template>

// frontend-react/src/components/layout/SidebarFooter.tsx
import { Settings, UserRound } from 'lucide-react'
import { useNavigate } from 'react-router'

import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { useAuthStore } from '@/stores/auth'
import { useSettingsStore } from '@/stores/settings'

export default function SidebarFooter() {
  const navigate = useNavigate()
  const username = useAuthStore((s) => s.username)
  const role = useAuthStore((s) => s.role)
  const logout = useAuthStore((s) => s.logout)
  const openSettings = useSettingsStore((s) => s.openSettings)

  async function onLogout() {
    await logout()
    navigate('/login', { replace: true })
  }

  return (
    <div className="flex h-14 shrink-0 items-center justify-between gap-2 border-t border-[var(--color-border)] bg-[var(--color-card)] px-3">
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <button
            type="button"
            className="flex min-w-0 cursor-pointer items-center gap-2 rounded-lg px-2 py-1.5 text-left transition-colors duration-200 hover:bg-slate-50"
          >
            <Avatar className="h-[30px] w-[30px] shrink-0 bg-[var(--color-primary)]">
              <AvatarFallback className="bg-[var(--color-primary)] text-white">
                <UserRound size={16} />
              </AvatarFallback>
            </Avatar>
            <span className="max-w-[7rem] truncate text-sm font-medium text-[var(--color-foreground)]">
              {username || '用户'}
            </span>
          </button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="start">
          <DropdownMenuItem disabled>资料（占位）</DropdownMenuItem>
          {role === 'admin' && (
            <>
              <DropdownMenuItem onSelect={() => navigate('/admin/users')}>用户管理</DropdownMenuItem>
              <DropdownMenuItem onSelect={() => navigate('/admin/databases')}>数据库管理</DropdownMenuItem>
            </>
          )}
          <DropdownMenuSeparator />
          <DropdownMenuItem onSelect={() => void onLogout()}>退出登录</DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      <Button
        variant="ghost"
        size="icon"
        className="h-10 w-10 rounded-full"
        aria-label="设置"
        onClick={openSettings}
      >
        <Settings size={18} />
      </Button>
    </div>
  )
}
