// frontend-react/src/components/layout/AppShell.tsx
import { MessageSquare, Plus } from 'lucide-react'
import type { ReactNode } from 'react'
import { useNavigate, useParams } from 'react-router'

import { Button } from '@/components/ui/button'
import { useSessionsStore } from '@/stores/sessions'
import SettingsDialog from './SettingsDialog'
import SidebarFooter from './SidebarFooter'

export default function AppShell({ children }: { children: ReactNode }) {
  const navigate = useNavigate()
  const params = useParams()
  const sessions = useSessionsStore((s) => s.sessions)
  const ensure = useSessionsStore((s) => s.ensure)

  function newChat() {
    const id = crypto.randomUUID()
    ensure(id)
    navigate(`/chat/${id}`)
  }

  function openSession(id: string) {
    navigate(`/chat/${id}`)
  }

  return (
    <div className="flex h-screen overflow-hidden bg-[var(--color-background)]">
      <aside className="flex w-64 shrink-0 flex-col border-r border-[var(--color-border)] bg-[var(--color-card)]">
        <div className="border-b border-[var(--color-border)] p-4">
          <div className="mb-4 flex items-center gap-2.5">
            <div
              className="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--color-primary)] text-white shadow-sm"
              aria-hidden="true"
            >
              <MessageSquare size={18} />
            </div>
            <div className="min-w-0">
              <div className="text-base font-semibold tracking-tight text-[var(--color-foreground)]">
                OpenChatBI
              </div>
              <div className="text-xs text-[var(--color-muted-foreground)]">智能数据分析对话</div>
            </div>
          </div>
          <Button className="h-10 w-full rounded-xl" onClick={newChat}>
            <Plus className="mr-1" size={16} />
            新建会话
          </Button>
        </div>

        <nav className="flex-1 overflow-y-auto p-2" aria-label="会话列表">
          {sessions.length === 0 ? (
            <div className="px-3 py-6 text-center text-xs text-[var(--color-muted-foreground)]">
              暂无会话，点击上方开始
            </div>
          ) : (
            sessions.map((s) => (
              <button
                key={s.id}
                type="button"
                className={
                  'group mb-0.5 flex w-full cursor-pointer items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm transition-colors duration-200 ' +
                  (params.sessionId === s.id
                    ? 'bg-[var(--color-muted)] font-medium text-[var(--color-primary)] shadow-[inset_3px_0_0_0_var(--color-primary)]'
                    : 'text-slate-600 hover:bg-slate-50')
                }
                onClick={() => openSession(s.id)}
              >
                <span className="truncate">{s.title}</span>
              </button>
            ))
          )}
        </nav>

        <SidebarFooter />
      </aside>

      <section className="flex min-h-0 min-w-0 flex-1 flex-col">{children}</section>

      <SettingsDialog />
    </div>
  )
}

// frontend/src/components/layout/AppShell.vue
<script setup lang="ts">
import { ChatDotRound, Plus } from '@element-plus/icons-vue'
import { useRoute, useRouter } from 'vue-router'

import SettingsDialog from './SettingsDialog.vue'
import SidebarFooter from './SidebarFooter.vue'
import { useSessionsStore } from '../../stores/sessions'

const route = useRoute()
const router = useRouter()
const sessionsStore = useSessionsStore()

function newChat() {
  const id = crypto.randomUUID()
  sessionsStore.ensure(id)
  void router.push({ name: 'chat-session', params: { sessionId: id } })
}

function openSession(id: string) {
  void router.push({ name: 'chat-session', params: { sessionId: id } })
}
</script>

<template>
  <div class="h-screen flex overflow-hidden bg-[var(--color-background)]">
    <aside
      class="w-64 shrink-0 flex flex-col border-r border-[var(--color-border)] bg-[var(--color-card)]"
    >
      <div class="p-4 border-b border-[var(--color-border)]">
        <div class="flex items-center gap-2.5 mb-4">
          <div
            class="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--color-primary)] text-white shadow-sm"
            aria-hidden="true"
          >
            <el-icon :size="18"><ChatDotRound /></el-icon>
          </div>
          <div class="min-w-0">
            <div class="text-base font-semibold tracking-tight text-[var(--color-foreground)]">
              OpenChatBI
            </div>
            <div class="text-xs text-[var(--color-muted-foreground)]">智能数据分析对话</div>
          </div>
        </div>
        <el-button type="primary" class="w-full !h-10 !rounded-xl" @click="newChat">
          <el-icon class="mr-1"><Plus /></el-icon>
          新建会话
        </el-button>
      </div>

      <nav class="flex-1 overflow-y-auto p-2" aria-label="会话列表">
        <div
          v-if="sessionsStore.sessions.length === 0"
          class="px-3 py-6 text-center text-xs text-[var(--color-muted-foreground)]"
        >
          暂无会话，点击上方开始
        </div>
        <button
          v-for="s in sessionsStore.sessions"
          :key="s.id"
          type="button"
          class="group mb-0.5 flex w-full cursor-pointer items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm transition-colors duration-200"
          :class="
            route.params.sessionId === s.id
              ? 'bg-[var(--color-muted)] font-medium text-[var(--color-primary)] shadow-[inset_3px_0_0_0_var(--color-primary)]'
              : 'text-slate-600 hover:bg-slate-50'
          "
          @click="openSession(s.id)"
        >
          <span class="truncate">{{ s.title }}</span>
        </button>
      </nav>

      <SidebarFooter />
    </aside>

    <section class="flex min-h-0 min-w-0 flex-1 flex-col">
      <slot />
    </section>

    <SettingsDialog />
  </div>
</template>
