// frontend-react/src/components/chat/InterruptDialog.tsx
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { useChatStore } from '@/stores/chat'

export default function InterruptDialog() {
  const lastInterrupt = useChatStore((s) => s.lastInterrupt)

  function close() {
    useChatStore.setState({ lastInterrupt: null })
  }

  return (
    <Dialog
      open={!!lastInterrupt}
      onOpenChange={(open) => {
        if (!open) close()
      }}
    >
      <DialogContent>
        <DialogHeader>
          <DialogTitle>需要你的确认</DialogTitle>
        </DialogHeader>
        <p className="whitespace-pre-wrap text-sm text-slate-700">{lastInterrupt?.text}</p>
        {lastInterrupt?.buttons?.length ? (
          <div className="flex flex-wrap gap-2">
            {lastInterrupt.buttons.map((b, i) => (
              <Badge key={i} variant="secondary">
                {String(b)}
              </Badge>
            ))}
          </div>
        ) : null}
        <DialogFooter>
          <Button onClick={close}>知道了</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// frontend/src/components/chat/InterruptDialog.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useChatStore } from '../../stores/chat'

const chat = useChatStore()
const visible = computed({
  get: () => !!chat.lastInterrupt,
  set: (v: boolean) => {
    if (!v) chat.lastInterrupt = null
  },
})
</script>

<template>
  <el-dialog v-model="visible" title="需要你的确认" width="480px">
    <p class="whitespace-pre-wrap text-sm text-slate-700">{{ chat.lastInterrupt?.text }}</p>
    <div v-if="chat.lastInterrupt?.buttons?.length" class="mt-3 flex flex-wrap gap-2">
      <el-tag v-for="(b, i) in chat.lastInterrupt?.buttons" :key="i">{{ String(b) }}</el-tag>
    </div>
    <template #footer>
      <el-button type="primary" @click="visible = false">知道了</el-button>
    </template>
  </el-dialog>
</template>
