// frontend/src/components/common/DemoWarehouseComposerHint.vue
<script setup lang="ts">
import { ref, watch } from 'vue'

import { fetchWarehouseStatus } from '../../api/warehouseStatus'
import { useAuthStore } from '../../stores/auth'

/** Short hint beside the chat composer when demo warehouse mode is on. */
const auth = useAuthStore()
const demoMode = ref(false)

watch(
  () => auth.isAuthenticated,
  (authenticated, _prev, onCleanup) => {
    if (!authenticated) {
      demoMode.value = false
      return
    }
    let cancelled = false
    onCleanup(() => {
      cancelled = true
    })
    void fetchWarehouseStatus()
      .then((status) => {
        if (!cancelled) demoMode.value = Boolean(status.demo_mode)
      })
      .catch(() => {
        if (!cancelled) demoMode.value = false
      })
  },
  { immediate: true },
)
</script>

<template>
  <p
    v-if="demoMode"
    role="status"
    aria-label="当前为演示数仓"
    class="text-xs font-medium text-amber-800"
  >
    当前为演示数仓
  </p>
</template>

// frontend-react/src/components/common/DemoWarehouseComposerHint.tsx
import { useEffect, useState } from 'react'

import { fetchWarehouseStatus } from '@/api/warehouseStatus'
import { cn } from '@/lib/utils'
import { useAuthStore } from '@/stores/auth'

/** Short hint beside the chat composer when demo warehouse mode is on. */
export default function DemoWarehouseComposerHint({ className }: { className?: string }) {
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated)
  const [demoMode, setDemoMode] = useState(false)

  useEffect(() => {
    if (!isAuthenticated) {
      setDemoMode(false)
      return
    }
    let cancelled = false
    void fetchWarehouseStatus()
      .then((status) => {
        if (!cancelled) setDemoMode(Boolean(status.demo_mode))
      })
      .catch(() => {
        if (!cancelled) setDemoMode(false)
      })
    return () => {
      cancelled = true
    }
  }, [isAuthenticated])

  if (!demoMode) return null

  return (
    <p
      role="status"
      aria-label="当前为演示数仓"
      className={cn('text-xs font-medium text-amber-800', className)}
    >
      当前为演示数仓
    </p>
  )
}
