// frontend/src/components/common/Markdown.vue
<script setup lang="ts">
import { computed } from 'vue'

import { renderMarkdown } from '../../lib/markdown'

const props = defineProps<{
  text: string
}>()

const html = computed(() => renderMarkdown(props.text))
</script>

<template>
  <div v-if="text" class="prose prose-sm prose-chat max-w-none break-words" v-html="html" />
</template>

// frontend-react/src/components/common/Markdown.tsx
import { useMemo } from 'react'

import { renderMarkdown } from '@/lib/markdown'
import { cn } from '@/lib/utils'

/** Renders sanitized markdown (headings, lists, tables, code, links, …) as styled HTML. */
export default function Markdown({ text, className }: { text: string; className?: string }) {
  const html = useMemo(() => renderMarkdown(text), [text])
  if (!text) return null
  return (
    <div
      className={cn('prose prose-sm prose-chat max-w-none break-words', className)}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
